#DAY 1 OF LEARNING PYTHON
#LEARNING ABOUT STRING MANIPULATION
#ESCAPE SEQUENCES, CONCATENATION, FORMATTING, METHODS
print("Hello" + " world") #CONCATENATION
print("Hello " * 5) #REPEATING STRINGS
print("Hello\nWorld") #ESCAPE SEQUENCE - NEW LINE
print("Hello\tWorld") #ESCAPE SEQUENCE - TAB
#STRING MANIPULATION EXERCISE